//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ankh {
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ankh.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Select Items to Add.
		/// </summary>
		internal static string AddDialogTitle {
			get {
				return ResourceManager.GetString("AddDialogTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Adding files to Subversion.
		/// </summary>
		internal static string AddingTitle {
			get {
				return ResourceManager.GetString("AddingTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Add Project from Subversion.
		/// </summary>
		internal static string AddProjectFromSubversion {
			get {
				return ResourceManager.GetString("AddProjectFromSubversion", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Would you like to add &apos;{0}&apos; to Subversion and mark it as managed?.
		/// </summary>
		internal static string AddSolutionXToSubversion {
			get {
				return ResourceManager.GetString("AddSolutionXToSubversion", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Adding files.
		/// </summary>
		internal static string AddTaskDialogTitle {
			get {
				return ResourceManager.GetString("AddTaskDialogTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Would you like to add&apos;{0}&apos; to existing working copy &apos;{1}&apos;?
		///Click Yes to add to the current working copy, and no to create a new working copy..
		/// </summary>
		internal static string AddXToExistingWcY {
			get {
				return ResourceManager.GetString("AddXToExistingWcY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to You are trying to annotate a binary file. Are you sure you want to continue?.
		/// </summary>
		internal static string AnnotateBinaryFileContinueAnywayText {
			get {
				return ResourceManager.GetString("AnnotateBinaryFileContinueAnywayText", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Binary file detected.
		/// </summary>
		internal static string AnnotateBinaryFileContinueAnywayTitle {
			get {
				return ResourceManager.GetString("AnnotateBinaryFileContinueAnywayTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Annotating.
		/// </summary>
		internal static string Annotating {
			get {
				return ResourceManager.GetString("Annotating", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Branch Project.
		/// </summary>
		internal static string BranchProject {
			get {
				return ResourceManager.GetString("BranchProject", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The commit processing can&apos;t commit &apos;{0}&apos;, because it is not managed by Subversion. Maybe you should refresh the status after applying changes with another client?.
		/// </summary>
		internal static string CantCommitUnversionedTargetX {
			get {
				return ResourceManager.GetString("CantCommitUnversionedTargetX", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to You can&apos;t update directories non recursively without the possibility of loosing files in your working copy. Would you like to update recursively?.
		/// </summary>
		internal static string CantUpdateDirectoriesNonRecursive {
			get {
				return ResourceManager.GetString("CantUpdateDirectoriesNonRecursive", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Checking Out.
		/// </summary>
		internal static string CheckingOut {
			get {
				return ResourceManager.GetString("CheckingOut", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Checking out Solution.
		/// </summary>
		internal static string CheckingOutSolution {
			get {
				return ResourceManager.GetString("CheckingOutSolution", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Cleaning Working Copy.
		/// </summary>
		internal static string CleaningWorkingCopy {
			get {
				return ResourceManager.GetString("CleaningWorkingCopy", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Commit Failed.
		/// </summary>
		internal static string CommitFailedCaption {
			get {
				return ResourceManager.GetString("CommitFailedCaption", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to You can only commit to one repository at a time.
		/// </summary>
		internal static string CommitSingleWc {
			get {
				return ResourceManager.GetString("CommitSingleWc", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Committed:.
		/// </summary>
		internal static string CommittedPrefix {
			get {
				return ResourceManager.GetString("CommittedPrefix", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Committing.
		/// </summary>
		internal static string CommitTitle {
			get {
				return ResourceManager.GetString("CommitTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Compare Files.
		/// </summary>
		internal static string CompareFilesTitle {
			get {
				return ResourceManager.GetString("CompareFilesTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Copying.
		/// </summary>
		internal static string Copying {
			get {
				return ResourceManager.GetString("Copying", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Create Patch.
		/// </summary>
		internal static string CreatePatchTitle {
			get {
				return ResourceManager.GetString("CreatePatchTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Creating Branch.
		/// </summary>
		internal static string CreatingBranch {
			get {
				return ResourceManager.GetString("CreatingBranch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Creating Directories.
		/// </summary>
		internal static string CreatingDirectories {
			get {
				return ResourceManager.GetString("CreatingDirectories", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Deleting.
		/// </summary>
		internal static string Deleting {
			get {
				return ResourceManager.GetString("Deleting", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Diffing.
		/// </summary>
		internal static string DiffTitle {
			get {
				return ResourceManager.GetString("DiffTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Directory deletes must be recursive and this would commit other files:.
		/// </summary>
		internal static string DirectoryDeleteAndNodeToKeep {
			get {
				return ResourceManager.GetString("DirectoryDeleteAndNodeToKeep", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Deleted directory: {0}.
		/// </summary>
		internal static string DirectoryDeleteX {
			get {
				return ResourceManager.GetString("DirectoryDeleteX", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Directory to commit: {0}.
		/// </summary>
		internal static string DirectoryToCommit {
			get {
				return ResourceManager.GetString("DirectoryToCommit", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Edit Conflict.
		/// </summary>
		internal static string EditConflictTitle {
			get {
				return ResourceManager.GetString("EditConflictTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Exporting.
		/// </summary>
		internal static string Exporting {
			get {
				return ResourceManager.GetString("Exporting", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Failed to save open documents before committing.
		/// </summary>
		internal static string FailedToSaveBeforeCommit {
			get {
				return ResourceManager.GetString("FailedToSaveBeforeCommit", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to  and .
		/// </summary>
		internal static string FileAnd {
			get {
				return ResourceManager.GetString("FileAnd", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ignore in Subversion.
		/// </summary>
		internal static string IgnoreCaption {
			get {
				return ResourceManager.GetString("IgnoreCaption", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ignore &amp;File ({0}).
		/// </summary>
		internal static string IgnoreFile {
			get {
				return ResourceManager.GetString("IgnoreFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ignore File&amp;type (*{0}).
		/// </summary>
		internal static string IgnoreFileType {
			get {
				return ResourceManager.GetString("IgnoreFileType", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ignore Folder ({0}).
		/// </summary>
		internal static string IgnoreFolder {
			get {
				return ResourceManager.GetString("IgnoreFolder", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Importing.
		/// </summary>
		internal static string ImportingTitle {
			get {
				return ResourceManager.GetString("ImportingTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Subversion does not allow to commit this combination of files and directories at once..
		/// </summary>
		internal static string InvalidCommitCombination {
			get {
				return ResourceManager.GetString("InvalidCommitCombination", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} (locked by &apos;{1}&apos;).
		/// </summary>
		internal static string ItemFileLocked {
			get {
				return ResourceManager.GetString("ItemFileLocked", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The following items could not be locked, because they were already locked. Do you want to try to steal the locks on these files?.
		/// </summary>
		internal static string ItemsAlreadyLocked {
			get {
				return ResourceManager.GetString("ItemsAlreadyLocked", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Locking.
		/// </summary>
		internal static string LockingTitle {
			get {
				return ResourceManager.GetString("LockingTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Would you like to mark &apos;{0}&apos; as managed by Subversion?.
		/// </summary>
		internal static string MarkXAsManaged {
			get {
				return ResourceManager.GetString("MarkXAsManaged", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Moving.
		/// </summary>
		internal static string Moving {
			get {
				return ResourceManager.GetString("Moving", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to You haven&apos;t entered an issue number.
		///Are you sure you want to commit without an issue number?.
		/// </summary>
		internal static string NoIssueNumber {
			get {
				return ResourceManager.GetString("NoIssueNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The specified path is not in a working copy; would you like to export the file instead?.
		/// </summary>
		internal static string NotInWorkingCopyExportInstead {
			get {
				return ResourceManager.GetString("NotInWorkingCopyExportInstead", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No Working Copy.
		/// </summary>
		internal static string NotInWorkingCopyTitle {
			get {
				return ResourceManager.GetString("NotInWorkingCopyTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to You are trying to commit conflicted items. Please review the conflicted files and resolve them, or remove the check when retrying the commit..
		/// </summary>
		internal static string OneOrMoreItemsConflicted {
			get {
				return ResourceManager.GetString("OneOrMoreItemsConflicted", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Please update the out of date items and then retry the commit..
		/// </summary>
		internal static string OutOfDateCaption {
			get {
				return ResourceManager.GetString("OutOfDateCaption", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Repository Post-Commit hook Result.
		/// </summary>
		internal static string PostCommitError {
			get {
				return ResourceManager.GetString("PostCommitError", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Reading Properties.
		/// </summary>
		internal static string ReadingProperties {
			get {
				return ResourceManager.GetString("ReadingProperties", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Relocating.
		/// </summary>
		internal static string RelocatingTitle {
			get {
				return ResourceManager.GetString("RelocatingTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Renaming.
		/// </summary>
		internal static string RenamingNodes {
			get {
				return ResourceManager.GetString("RenamingNodes", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Retrieving Conflict Details.
		/// </summary>
		internal static string RetrievingConflictDetails {
			get {
				return ResourceManager.GetString("RetrievingConflictDetails", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Retrieving File for Comparison.
		/// </summary>
		internal static string RetrievingFileForComparison {
			get {
				return ResourceManager.GetString("RetrievingFileForComparison", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Retrieving Multiple Versions of One File.
		/// </summary>
		internal static string RetrievingMultipleVersionsOfFile {
			get {
				return ResourceManager.GetString("RetrievingMultipleVersionsOfFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Retrieving Repository Root.
		/// </summary>
		internal static string RetrievingRepositoryRoot {
			get {
				return ResourceManager.GetString("RetrievingRepositoryRoot", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Select Items to Revert.
		/// </summary>
		internal static string RevertDialogTitle {
			get {
				return ResourceManager.GetString("RevertDialogTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Reverting.
		/// </summary>
		internal static string Reverting {
			get {
				return ResourceManager.GetString("Reverting", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Comparing Files.
		/// </summary>
		internal static string RunningDiff {
			get {
				return ResourceManager.GetString("RunningDiff", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Not to commit: {0}.
		/// </summary>
		internal static string ShouldNotCommitX {
			get {
				return ResourceManager.GetString("ShouldNotCommitX", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Storing Property Values.
		/// </summary>
		internal static string StoringPropertyValues {
			get {
				return ResourceManager.GetString("StoringPropertyValues", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Switching.
		/// </summary>
		internal static string SwitchingTitle {
			get {
				return ResourceManager.GetString("SwitchingTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The conflict in &apos;{0}&apos; is already resolved..
		/// </summary>
		internal static string TheConflictInXIsAlreadyResolved {
			get {
				return ResourceManager.GetString("TheConflictInXIsAlreadyResolved", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The selected items will be deleted permanently..
		/// </summary>
		internal static string TheSelectedItemsWillBeDeletedPermanently {
			get {
				return ResourceManager.GetString("TheSelectedItemsWillBeDeletedPermanently", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Unified Diff.
		/// </summary>
		internal static string UnifiedDiffTitle {
			get {
				return ResourceManager.GetString("UnifiedDiffTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Unlock Files.
		/// </summary>
		internal static string UnlockTitle {
			get {
				return ResourceManager.GetString("UnlockTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated to:.
		/// </summary>
		internal static string UpdatedToTitle {
			get {
				return ResourceManager.GetString("UpdatedToTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Update Files.
		/// </summary>
		internal static string UpdateFilesTitle {
			get {
				return ResourceManager.GetString("UpdateFilesTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Update Folder.
		/// </summary>
		internal static string UpdateFolder {
			get {
				return ResourceManager.GetString("UpdateFolder", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Folder:.
		/// </summary>
		internal static string UpdateFolderLabel {
			get {
				return ResourceManager.GetString("UpdateFolderLabel", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Update Project.
		/// </summary>
		internal static string UpdateProject {
			get {
				return ResourceManager.GetString("UpdateProject", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updating Folder.
		/// </summary>
		internal static string UpdatingFolder {
			get {
				return ResourceManager.GetString("UpdatingFolder", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updating Project.
		/// </summary>
		internal static string UpdatingProject {
			get {
				return ResourceManager.GetString("UpdatingProject", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updating Solution.
		/// </summary>
		internal static string UpdatingSolution {
			get {
				return ResourceManager.GetString("UpdatingSolution", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updating.
		/// </summary>
		internal static string UpdatingTitle {
			get {
				return ResourceManager.GetString("UpdatingTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Upgrading Working Copy.
		/// </summary>
		internal static string UpgradingWorkingCopy {
			get {
				return ResourceManager.GetString("UpgradingWorkingCopy", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to While committing: {0}.
		/// </summary>
		internal static string WhileCommittingX {
			get {
				return ResourceManager.GetString("WhileCommittingX", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Working Copy: {0} (from repository {1}).
		/// </summary>
		internal static string WorkingCopyXFromRepositoryY {
			get {
				return ResourceManager.GetString("WorkingCopyXFromRepositoryY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Would you like to add {0} to the svn:ignore property on &apos;{1}&apos;?.
		/// </summary>
		internal static string WouldYouLikeToAddXToTheIgnorePropertyOnY {
			get {
				return ResourceManager.GetString("WouldYouLikeToAddXToTheIgnorePropertyOnY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &apos;{0}&apos; will be deleted permanently..
		/// </summary>
		internal static string XWillBeDeletedPermanently {
			get {
				return ResourceManager.GetString("XWillBeDeletedPermanently", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to You can download the latest AnkhSVN release on http://ankhsvn.net/downloads.
		/// </summary>
		internal static string YouCanDownloadAnkh {
			get {
				return ResourceManager.GetString("YouCanDownloadAnkh", resourceCulture);
			}
		}
	}
}
