//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ankh.UI {
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ankh.UI.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Added.
		/// </summary>
		internal static string Added {
			get {
				return ResourceManager.GetString("Added", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap AddWorldButton {
			get {
				object obj = ResourceManager.GetObject("AddWorldButton", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Subversion can store your repository logon credentials and other server authentication settings in its authentication store. It will automatically try to logon using this information when you connect to a repository. On Windows your passwords are encrypted using your Windows Credentials..
		/// </summary>
		internal static string AuthCacheHelp {
			get {
				return ResourceManager.GetString("AuthCacheHelp", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Author.
		/// </summary>
		internal static string AuthorColumn {
			get {
				return ResourceManager.GetString("AuthorColumn", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Author: {0}.
		/// </summary>
		internal static string AuthorHead {
			get {
				return ResourceManager.GetString("AuthorHead", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Base.
		/// </summary>
		internal static string BaseVersion {
			get {
				return ResourceManager.GetString("BaseVersion", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap Busy {
			get {
				object obj = ResourceManager.GetObject("Busy", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Change.
		/// </summary>
		internal static string ChangeColumn {
			get {
				return ResourceManager.GetString("ChangeColumn", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Change &amp;List.
		/// </summary>
		internal static string ChangeListColumn {
			get {
				return ResourceManager.GetString("ChangeListColumn", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Committed.
		/// </summary>
		internal static string CommittedVersion {
			get {
				return ResourceManager.GetString("CommittedVersion", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Compare revision {0} to {1}.
		/// </summary>
		internal static string CompareRevisionXToY {
			get {
				return ResourceManager.GetString("CompareRevisionXToY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Description.
		/// </summary>
		internal static string ConflictDescriptionColumn {
			get {
				return ResourceManager.GetString("ConflictDescriptionColumn", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap Conflicts {
			get {
				object obj = ResourceManager.GetObject("Conflicts", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Con&amp;flict Type.
		/// </summary>
		internal static string ConflictTypeColumn {
			get {
				return ResourceManager.GetString("ConflictTypeColumn", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Create &amp;branch/tag from revision {0}.
		/// </summary>
		internal static string CreateBranchTagFromRevisionX {
			get {
				return ResourceManager.GetString("CreateBranchTagFromRevisionX", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Creating Directory.
		/// </summary>
		internal static string CreatingDirectory {
			get {
				return ResourceManager.GetString("CreatingDirectory", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Modified.
		/// </summary>
		internal static string DateColumn {
			get {
				return ResourceManager.GetString("DateColumn", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Date.
		/// </summary>
		internal static string DateVersion {
			get {
				return ResourceManager.GetString("DateVersion", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Deleted.
		/// </summary>
		internal static string Deleted {
			get {
				return ResourceManager.GetString("Deleted", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap DirUpButton {
			get {
				object obj = ResourceManager.GetObject("DirUpButton", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Enter a valid path (like &apos;C:\MyWork&apos;).
		/// </summary>
		internal static string EnterValidPath {
			get {
				return ResourceManager.GetString("EnterValidPath", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Enter a valid url (like &apos;http://myserver/svn/repos/path&apos;).
		/// </summary>
		internal static string EnterValidUrl {
			get {
				return ResourceManager.GetString("EnterValidUrl", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Revision.
		/// </summary>
		internal static string ExplicitVersion {
			get {
				return ResourceManager.GetString("ExplicitVersion", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to File Folder.
		/// </summary>
		internal static string ExplorerDirectoryName {
			get {
				return ResourceManager.GetString("ExplorerDirectoryName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Fol&amp;der.
		/// </summary>
		internal static string FolderColumn {
			get {
				return ResourceManager.GetString("FolderColumn", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Full Path.
		/// </summary>
		internal static string FullPathColumn {
			get {
				return ResourceManager.GetString("FullPathColumn", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Latest Version.
		/// </summary>
		internal static string HeadVersion {
			get {
				return ResourceManager.GetString("HeadVersion", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Issue:.
		/// </summary>
		internal static string IssueLabelText {
			get {
				return ResourceManager.GetString("IssueLabelText", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap Issues {
			get {
				object obj = ResourceManager.GetObject("Issues", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Local Change (uncommitted).
		/// </summary>
		internal static string LocalChange {
			get {
				return ResourceManager.GetString("LocalChange", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Local Change.
		/// </summary>
		internal static string LocalChangeColumn {
			get {
				return ResourceManager.GetString("LocalChangeColumn", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Local Repositories.
		/// </summary>
		internal static string LocalRepositories {
			get {
				return ResourceManager.GetString("LocalRepositories", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Loc&amp;ked.
		/// </summary>
		internal static string LockedColumn {
			get {
				return ResourceManager.GetString("LockedColumn", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Locked.
		/// </summary>
		internal static string LockedValue {
			get {
				return ResourceManager.GetString("LockedValue", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Lock Owner.
		/// </summary>
		internal static string LockOwnerColumn {
			get {
				return ResourceManager.GetString("LockOwnerColumn", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Author: {0}.
		/// </summary>
		internal static string LogAuthor {
			get {
				return ResourceManager.GetString("LogAuthor", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Date: {0:F}.
		/// </summary>
		internal static string LogDate {
			get {
				return ResourceManager.GetString("LogDate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Message:.
		/// </summary>
		internal static string LogMessagePrefix {
			get {
				return ResourceManager.GetString("LogMessagePrefix", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to  ---- .
		/// </summary>
		internal static string LogMessageSuffix {
			get {
				return ResourceManager.GetString("LogMessageSuffix", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Changed.
		/// </summary>
		internal static string LogModified {
			get {
				return ResourceManager.GetString("LogModified", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to File Changed.
		/// </summary>
		internal static string LogModifiedTextOnly {
			get {
				return ResourceManager.GetString("LogModifiedTextOnly", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Revision: {0}.
		/// </summary>
		internal static string LogRevision {
			get {
				return ResourceManager.GetString("LogRevision", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Modified.
		/// </summary>
		internal static string ModifiedColumn {
			get {
				return ResourceManager.GetString("ModifiedColumn", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to You are trying to commit files from several Subversion working copies.
		///
		///Subversion does not support committing these changes in a single revision, but we can commit it as multiple revisions.
		///
		///Which working copies would you like to commit with the current log message?.
		/// </summary>
		internal static string MultiWorkingCopyCommit {
			get {
				return ResourceManager.GetString("MultiWorkingCopyCommit", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to My Computer.
		/// </summary>
		internal static string MyComputer {
			get {
				return ResourceManager.GetString("MyComputer", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Name.
		/// </summary>
		internal static string NameColumn {
			get {
				return ResourceManager.GetString("NameColumn", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;{0} files&gt;.
		/// </summary>
		internal static string NrOfFileInfo {
			get {
				return ResourceManager.GetString("NrOfFileInfo", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;{0} files below &apos;{1}&apos;&gt;.
		/// </summary>
		internal static string NrOfFilesBelow {
			get {
				return ResourceManager.GetString("NrOfFilesBelow", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Path.
		/// </summary>
		internal static string PathColumn {
			get {
				return ResourceManager.GetString("PathColumn", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap Plus {
			get {
				object obj = ResourceManager.GetObject("Plus", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Previous.
		/// </summary>
		internal static string PreviousVersion {
			get {
				return ResourceManager.GetString("PreviousVersion", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to P&amp;roject.
		/// </summary>
		internal static string ProjectColumn {
			get {
				return ResourceManager.GetString("ProjectColumn", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Properties Changed.
		/// </summary>
		internal static string PropertiesModified {
			get {
				return ResourceManager.GetString("PropertiesModified", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap RecentChanges {
			get {
				object obj = ResourceManager.GetObject("RecentChanges", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap RefreshButton {
			get {
				object obj = ResourceManager.GetObject("RefreshButton", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Refreshed: {0}.
		/// </summary>
		internal static string RefreshTimeX {
			get {
				return ResourceManager.GetString("RefreshTimeX", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Remote Change.
		/// </summary>
		internal static string RemoteChangeColumn {
			get {
				return ResourceManager.GetString("RemoteChangeColumn", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Replaced.
		/// </summary>
		internal static string Replaced {
			get {
				return ResourceManager.GetString("Replaced", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Specify the repository URL or select one of the repository providers (if available)..
		/// </summary>
		internal static string RepoProviderPageHeaderMessage {
			get {
				return ResourceManager.GetString("RepoProviderPageHeaderMessage", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Repository Provider Selection.
		/// </summary>
		internal static string RepoProviderPageHeaderTitle {
			get {
				return ResourceManager.GetString("RepoProviderPageHeaderTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Select a repository..
		/// </summary>
		internal static string RepoSelectionPageHeaderMessage {
			get {
				return ResourceManager.GetString("RepoSelectionPageHeaderMessage", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Repository Selection.
		/// </summary>
		internal static string RepoSelectionPageHeaderTitle {
			get {
				return ResourceManager.GetString("RepoSelectionPageHeaderTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap RepositoryWizardHeader {
			get {
				object obj = ResourceManager.GetObject("RepositoryWizardHeader", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Repository Selection Wizard.
		/// </summary>
		internal static string RepoTitle {
			get {
				return ResourceManager.GetString("RepoTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Retrieving Remote Status.
		/// </summary>
		internal static string RetrievingRemoteStatus {
			get {
				return ResourceManager.GetString("RetrievingRemoteStatus", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Retrieving Repository Root.
		/// </summary>
		internal static string RetrievingRepositoryRoot {
			get {
				return ResourceManager.GetString("RetrievingRepositoryRoot", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Retrieving Revision Properties.
		/// </summary>
		internal static string RetrievingRevisionProperties {
			get {
				return ResourceManager.GetString("RetrievingRevisionProperties", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Revert changes from revision {0}.
		/// </summary>
		internal static string RevertChangesFromRevisionX {
			get {
				return ResourceManager.GetString("RevertChangesFromRevisionX", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Revert changes from revision {0} to {1}.
		/// </summary>
		internal static string RevertChangesFromRevisionXToY {
			get {
				return ResourceManager.GetString("RevertChangesFromRevisionXToY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Reverting.
		/// </summary>
		internal static string Reverting {
			get {
				return ResourceManager.GetString("Reverting", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Revision.
		/// </summary>
		internal static string RevisionColumn {
			get {
				return ResourceManager.GetString("RevisionColumn", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Properties of revision {0} from &apos;{1}&apos;.
		/// </summary>
		internal static string RevisionXPropertiesFromY {
			get {
				return ResourceManager.GetString("RevisionXPropertiesFromY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Revision: {0}.
		/// </summary>
		internal static string RevisonHead {
			get {
				return ResourceManager.GetString("RevisonHead", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Subversion Repositories.
		/// </summary>
		internal static string RootName {
			get {
				return ResourceManager.GetString("RootName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Size.
		/// </summary>
		internal static string SizeColumn {
			get {
				return ResourceManager.GetString("SizeColumn", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Solution &apos;{0}&apos;.
		/// </summary>
		internal static string SolutionX {
			get {
				return ResourceManager.GetString("SolutionX", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap SourceFiles {
			get {
				object obj = ResourceManager.GetObject("SourceFiles", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Deleted.
		/// </summary>
		internal static string StateDeleted {
			get {
				return ResourceManager.GetString("StateDeleted", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Modified.
		/// </summary>
		internal static string StateModified {
			get {
				return ResourceManager.GetString("StateModified", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to New.
		/// </summary>
		internal static string StateNew {
			get {
				return ResourceManager.GetString("StateNew", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Unmodified.
		/// </summary>
		internal static string StateUnmodified {
			get {
				return ResourceManager.GetString("StateUnmodified", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap Status_Error {
			get {
				object obj = ResourceManager.GetObject("Status_Error", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap Status_Exclamation {
			get {
				object obj = ResourceManager.GetObject("Status_Exclamation", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap Status_Ok {
			get {
				object obj = ResourceManager.GetObject("Status_Ok", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap Status_Suggestion {
			get {
				object obj = ResourceManager.GetObject("Status_Suggestion", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap Status_Warning {
			get {
				object obj = ResourceManager.GetObject("Status_Warning", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Switch to revision {0}.
		/// </summary>
		internal static string SwitchToRevisionX {
			get {
				return ResourceManager.GetString("SwitchToRevisionX", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The selected Credentials will be removed. Would you like to continue?.
		/// </summary>
		internal static string TheSelectedCredentialsWillBeRemoved {
			get {
				return ResourceManager.GetString("TheSelectedCredentialsWillBeRemoved", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Time: {0}.
		/// </summary>
		internal static string TimeHead {
			get {
				return ResourceManager.GetString("TimeHead", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Type.
		/// </summary>
		internal static string TypeColumn {
			get {
				return ResourceManager.GetString("TypeColumn", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updating Revision Properties.
		/// </summary>
		internal static string UpdatingRevisionProperties {
			get {
				return ResourceManager.GetString("UpdatingRevisionProperties", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap VersionButton {
			get {
				object obj = ResourceManager.GetObject("VersionButton", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Compare.
		/// </summary>
		internal static string WhitespaceCompare {
			get {
				return ResourceManager.GetString("WhitespaceCompare", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ignore all Whitespace.
		/// </summary>
		internal static string WhitespaceIgnoreAllWhitespace {
			get {
				return ResourceManager.GetString("WhitespaceIgnoreAllWhitespace", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ignore Changes.
		/// </summary>
		internal static string WhitespaceIgnoreChanges {
			get {
				return ResourceManager.GetString("WhitespaceIgnoreChanges", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Working Copy.
		/// </summary>
		internal static string WorkingCopyColumn {
			get {
				return ResourceManager.GetString("WorkingCopyColumn", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Working.
		/// </summary>
		internal static string WorkingVersion {
			get {
				return ResourceManager.GetString("WorkingVersion", resourceCulture);
			}
		}
	}
}
